import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { cleanup, render, screen, waitFor, fireEvent } from '@testing-library/react';
const account = vi.hoisted(() => ({ isLoaded: true, isSignedIn: true, userId: 'user_a' }));
vi.mock('@clerk/nextjs', () => ({ useAuth: () => account, useClerk: () => ({ openSignUp: vi.fn() }), Show: () => null, SignInButton: () => null, SignUpButton: () => null, UserButton: () => null }));
vi.mock('next/navigation', () => ({ useRouter: () => ({ push: vi.fn() }) }));
vi.mock('@/app/daily-nutrition-calculator', () => ({ DailyNutritionCalculator: () => null }));
import Home from '@/app/page';
import { meal } from './fixtures';
beforeEach(() => { localStorage.clear(); account.userId = 'user_a'; });
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
it('clears the previous account view and ignores its delayed history response', async () => {
  let finish!: (response: Response) => void;
  const today = new Date().toISOString();
  const fetcher = vi.fn().mockImplementationOnce(() => new Promise<Response>((resolve) => { finish = resolve; })).mockResolvedValue(Response.json({ meals: [{ ...meal, createdAt: today, title: 'Account B lunch' }] }));
  vi.stubGlobal('fetch', fetcher);
  localStorage.setItem('platewise:recent-meals:user_a', JSON.stringify([{ ...meal, createdAt: today, title: 'Account A lunch' }]));
  const view = render(<Home />);
  fireEvent.click(screen.getByLabelText('View recent meals'));
  await waitFor(() => expect(screen.getByText('Account A lunch')).toBeTruthy());
  await waitFor(() => expect(fetcher).toHaveBeenCalledTimes(1));
  account.userId = 'user_b';
  view.rerender(<Home />);
  expect(screen.queryByText('Account A lunch')).toBeNull();
  fireEvent.click(screen.getByLabelText('View recent meals'));
  await waitFor(() => expect(screen.getByText('Account B lunch')).toBeTruthy());
  finish(Response.json({ meals: [{ ...meal, createdAt: today, title: 'Account A lunch' }] }));
  await waitFor(() => expect(localStorage.getItem('platewise:recent-meals:user_b')).toContain('Account B lunch'));
  expect(screen.queryByText('Account A lunch')).toBeNull();
});
